source = ~/.config/omarchy/current/theme/hyprlock.conf
 
general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = true
    bezier = smoothOut, 0.4, 0.0, 0.2, 1.0
    animation = fadeIn, 1, 4, smoothOut
    animation = inputFieldDots, 1, 2, smoothOut
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%H:%M')</span>"
    color = rgba(220, 224, 217, 0.9)
    font_size = 72
    font_family = CaskaydiaMono Nerd Font
    position = 0, 310
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "<span>$(date +'%A, %d de %B')</span>"
    color = rgba(220, 224, 217, 0.6)
    font_size = 18
    font_family = CaskaydiaMono Nerd Font
    position = 0, 220
    halign = center
    valign = center
}

image {
    monitor =
    path = /tmp/hyprlock-art.jpg
    size = 140
    rounding = 10
    position = 0, 90
    halign = center
    valign = center
    border_size = 3
    border_color = rgba(166, 124, 82, 0.8)
}

label {
    monitor =
    text = cmd[update:5000] echo "<span>$($HOME/.local/bin/hyprlock-track)</span>"
    color = rgba(166, 124, 82, 0.85)
    font_size = 14
    font_family = CaskaydiaMono Nerd Font
    position = 0, -30
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 650, 100
    position = 0, -140
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text = <span> Enter Password 󰈷 </span>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 8
    shadow_passes = 2
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
