general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(2a2e1e)
}

label {
    monitor =
    text = $TIME
    color = rgb(dce0d9)
    font_family = JetBrainsMono Nerd Font
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -30
    halign = center
    valign = center
    inner_color = rgb(2a2e1e)
    outer_color = rgb(a67c52)
    font_color = rgb(dce0d9)
    check_color = rgb(a67c52)
    fail_color = rgb(c25d44)
    font_family = JetBrainsMono Nerd Font
    outline_thickness = 2
    rounding = 12
    placeholder_text = Senha
    fail_text = Tente novamente
}
