general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(fbf1c7)
}

label {
    monitor =
    text = $TIME
    color = rgb(3c3836)
    font_family = JetBrainsMono Nerd Font
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -30
    halign = center
    valign = center
    inner_color = rgb(fbf1c7)
    outer_color = rgb(b57614)
    font_color = rgb(3c3836)
    check_color = rgb(b57614)
    fail_color = rgb(9d0006)
    font_family = JetBrainsMono Nerd Font
    outline_thickness = 2
    rounding = 12
    placeholder_text = Senha
    fail_text = Tente novamente
}
