-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Control your input devices

-- See https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        -- Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
        kb_layout = "br",
        kb_options = "compose:caps",
        -- ,grp:alts_toggle
        -- Change speed of keyboard repeat
        repeat_rate = 40,
        repeat_delay = 600,
        -- Start with numlock on by default
        numlock_by_default = true,
        -- Increase sensitity for mouse/trackpack (default: 0)
        -- sensitivity = 0.35
        touchpad = {
            -- Use natural (inverse) scrolling
            -- natural_scroll = true
            -- Use two-finger clicks for right-click instead of lower-right corner
            -- clickfinger_behavior = true
            -- Control the speed of your scrolling
            scroll_factor = 0.4,
        },
    },
})

-- Scroll nicely in the terminal

hl.window_rule({
    name  = "scroll_touchpad_1_5_31",
    match = {
        class = "(Alacritty|kitty|foot)",
    },
    scroll_touchpad = 1.5,
})

hl.window_rule({
    name  = "scroll_touchpad_0_2_32",
    match = {
        class = "com.mitchellh.ghostty",
    },
    scroll_touchpad = 0.2,
})

-- Enable touchpad gestures for changing workspaces

-- See https://wiki.hyprland.org/Configuring/Gestures/

-- gesture = 3, horizontal, workspace
