-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Change the default Omarchy look'n'feel

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 12,
        -- Use master layout instead of dwindle
        -- layout = master
        col = {
            active_border = { colors = { "rgba(a67c52ee)", "rgba(d4a574ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = 0.85,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            vibrancy = 0.15,
        },
        shadow = {
            enabled = true,
            range = 8,
            render_power = 4,
            color = "rgba(a67c52bb)",
            color_inactive = "rgba(00000044)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#layout

hl.config({
    layout = {
        -- Avoid overly wide single-window layouts on wide screens
        -- single_window_aspect_ratio = 1 1
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
    },
})
hl.curve("overshot", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.curve("smooth", {
    type = "bezier",
    points = { { 0.4, 0.0 }, { 0.2, 1.0 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "smooth", style = "slide" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "smooth", style = "slidefadevert 25" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 6, bezier = "smooth", style = "slidefadevert 25" })
hl.animation({ leaf = "layers", enabled = true, speed = 4, bezier = "smooth", style = "fade" })
