-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Applications

hl.unbind("SUPER + SPACE")
hl.unbind("SUPER + SPACE")
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-menu"))

hl.unbind("SUPER + SHIFT + SPACE")
hl.unbind("SUPER + SHIFT + SPACE")
hl.bind("SUPER + SHIFT + SPACE", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-menu"))

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("ghostty"))

hl.bind("SUPER + ALT + RETURN", hl.dsp.exec_cmd("ghostty -e tmux new-session -A -s main"))

hl.bind("SUPER + CTRL + RETURN", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchtmux"))

hl.bind("SUPER + SHIFT + RETURN", hl.dsp.exec_cmd("librewolf"))

hl.bind("SUPER + grave", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchterm"))

hl.bind("SUPER + B", hl.dsp.exec_cmd("librewolf"))

hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("librewolf"))

hl.bind("SUPER + SHIFT + ALT + B", hl.dsp.exec_cmd("librewolf --private-window"))

hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("ghostty -e yazi"))

hl.bind("SUPER + N", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchnvim"))

hl.bind("SUPER + E", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchwork"))

hl.bind("SUPER + H", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchkeys"))

hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("ghostty -e nvim"))

hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("ghostty -e btop"))

hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("ghostty -e emacsclient -nw --eval '(nf/daily-note)'"))

hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("spotify"))

hl.bind("SUPER + C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/scratchtmux"))

-- Windows

hl.bind("SUPER + W", hl.dsp.window.close())

hl.bind("SUPER + F", hl.dsp.window.fullscreen())

hl.bind("SUPER + T", hl.dsp.window.float())

hl.bind("SUPER + LEFT", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER + RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER + UP", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER + DOWN", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + SHIFT + LEFT", hl.dsp.window.move({ direction = "left" }))

hl.bind("SUPER + SHIFT + RIGHT", hl.dsp.window.move({ direction = "right" }))

hl.bind("SUPER + SHIFT + UP", hl.dsp.window.move({ direction = "up" }))

hl.bind("SUPER + SHIFT + DOWN", hl.dsp.window.move({ direction = "down" }))

hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }))

hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

-- Workspaces

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))

-- Desktop

hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hyprlock"))

hl.bind("SUPER + CTRL + W", hl.dsp.exec_cmd("ghostty -e nmtui"))

hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("ghostty -e bluetui"))

hl.bind("SUPER + CTRL + A", hl.dsp.exec_cmd("ghostty -e wiremix"))

hl.bind("SUPER + CTRL + X", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-power"))

hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-power"))

hl.bind("SUPER + CTRL + P", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-power"))

hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-clipboard"))

hl.bind("SUPER + CTRL + C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-screenshot"))

hl.bind("SUPER + comma", hl.dsp.exec_cmd("quickshell ipc call notifications dismissOne"))

hl.bind("SUPER + SHIFT + comma", hl.dsp.exec_cmd("quickshell ipc call notifications dismissAll"))

hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("ghostty -e deck status"))

hl.bind("SUPER + SHIFT + ALT + P", hl.dsp.exec_cmd("ghostty -e bash -lc 'read -p \"Capture: \" t && deck capture \"$t\"'"))

hl.bind("SUPER + SHIFT + CTRL + P", hl.dsp.exec_cmd("ghostty -e bash -lc 'deck phone push-status && deck phone push-contabo'"))

hl.bind("SUPER + F10", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"))

hl.bind("F10", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-screenshot"))

-- Media and hardware

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true, locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Screenshots

hl.bind("PRINT", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-screenshot"))

hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/desktop-screenshot full"))
