-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Hyprland standalone configuration.

-- This file is the standalone Hyprland session entrypoint.

hl.monitor({
    output   = "eDP-1",
    mode     = "1366x768@60.01",
    position = "1295x720",
    scale    = 1.25,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1600x900@60.0",
    position = "1280x0",
    scale    = 1.25,
})

hl.env("XDPH_IGNORE_CURSOR", 1)

hl.env("GDK_SCALE", 1)

require("input")
require("looknfeel")
require("windowrules")
dofile(os.getenv("HOME") .. "/.config/hypr/standalone-bindings.lua")
dofile(os.getenv("HOME") .. "/.config/hypr/standalone-autostart.lua")

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})
