-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Scratchpads

hl.window_rule({
    name  = "workspace_special_sc_7",
    match = {
        title = "^__scratchterm$",
    },
    workspace = "special:scratchterm silent",
})

hl.window_rule({
    name  = "float_on_8",
    match = {
        title = "^__scratchterm$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_930_510_9",
    match = {
        title = "^__scratchterm$",
    },
    size = { "monitor_w*0.73", "monitor_h*0.71" },
})

hl.window_rule({
    name  = "center_on_10",
    match = {
        title = "^__scratchterm$",
    },
    center = true,
})

hl.window_rule({
    name  = "workspace_special_nv_12",
    match = {
        title = "^__scratchnvim$",
    },
    workspace = "special:nvim silent",
})

hl.window_rule({
    name  = "float_on_13",
    match = {
        title = "^__scratchnvim$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_14",
    match = {
        title = "^__scratchnvim$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_15",
    match = {
        title = "^__scratchnvim$",
    },
    center = true,
})

hl.window_rule({
    name  = "workspace_special_wo_22",
    match = {
        title = "^__scratchwork$",
    },
    workspace = "special:work-nvim silent",
})

hl.window_rule({
    name  = "float_on_23",
    match = {
        title = "^__scratchwork$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_24",
    match = {
        title = "^__scratchwork$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_25",
    match = {
        title = "^__scratchwork$",
    },
    center = true,
})

hl.window_rule({
    name  = "workspace_special_ke_27",
    match = {
        title = "^__scratchkeys$",
    },
    workspace = "special:keys silent",
})

hl.window_rule({
    name  = "float_on_28",
    match = {
        title = "^__scratchkeys$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_29",
    match = {
        title = "^__scratchkeys$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_30",
    match = {
        title = "^__scratchkeys$",
    },
    center = true,
})

hl.window_rule({
    name  = "workspace_special_ik_32",
    match = {
        title = "^__scratchikhal$",
    },
    workspace = "special:ikhal silent",
})

hl.window_rule({
    name  = "float_on_33",
    match = {
        title = "^__scratchikhal$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_34",
    match = {
        title = "^__scratchikhal$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_35",
    match = {
        title = "^__scratchikhal$",
    },
    center = true,
})

hl.window_rule({
    name  = "workspace_special_sp_37",
    match = {
        title = "^__scratchspotify$",
    },
    workspace = "special:spotify silent",
})

hl.window_rule({
    name  = "float_on_38",
    match = {
        title = "^__scratchspotify$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_39",
    match = {
        title = "^__scratchspotify$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_40",
    match = {
        title = "^__scratchspotify$",
    },
    center = true,
})

-- khal calendar popup

hl.window_rule({
    name  = "float_on_44",
    match = {
        class = "^org.khal.calendar$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_700_420_45",
    match = {
        class = "^org.khal.calendar$",
    },
    size = { "monitor_w*0.55", "monitor_h*0.58" },
})

hl.window_rule({
    name  = "move_100_-715_35_46",
    match = {
        class = "^org.khal.calendar$",
    },
    move = { "100%-715", 35 },
})

hl.window_rule({
    name  = "animation_slide_47",
    match = {
        class = "^org.khal.calendar$",
    },
    animation = "slide",
})

-- Spotify player — scratchpad (Super+M)

hl.window_rule({
    name  = "workspace_special_sp_50",
    match = {
        class = "^spotify-player$",
    },
    workspace = "special:spotify silent",
})

hl.window_rule({
    name  = "float_on_51",
    match = {
        class = "^spotify-player$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1100_650_52",
    match = {
        class = "^spotify-player$",
    },
    size = { "monitor_w*0.86", "monitor_h*0.9" },
})

hl.window_rule({
    name  = "center_on_53",
    match = {
        class = "^spotify-player$",
    },
    center = true,
})

hl.window_rule({
    name  = "animation_slide_54",
    match = {
        class = "^spotify-player$",
    },
    animation = "slide",
})

-- tmux agent/vault scratchpad (Super+C)

hl.window_rule({
    name  = "workspace_special_tmux_55",
    match = {
        title = "^__scratchtmux$",
    },
    workspace = "special:scratchtmux silent",
})

hl.window_rule({
    name  = "float_on_56",
    match = {
        title = "^__scratchtmux$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_1024_570_57",
    match = {
        title = "^__scratchtmux$",
    },
    size = { "monitor_w*0.8", "monitor_h*0.79" },
})

hl.window_rule({
    name  = "center_on_58",
    match = {
        title = "^__scratchtmux$",
    },
    center = true,
})
