# Yerba Mate light — Terere.
background = "fbf1c7"
foreground = "3c3836"
accent = "b57614"
muted = "928374"
error = "9d0006"
font = "JetBrainsMono Nerd Font"

black = "3c3836"
red = "9d0006"
green = "79740e"
yellow = "b57614"
blue = "076678"
magenta = "8f3f71"
cyan = "427b58"
white = "fbf1c7"
bright_black = "928374"
bright_red = "cc241d"
bright_green = "98971a"
bright_yellow = "d79921"
bright_blue = "458588"
bright_magenta = "b16286"
bright_cyan = "689d6a"
bright_white = "f9f5d7"
