general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(${background})
}

label {
    monitor =
    text = $$TIME
    color = rgb(${foreground})
    font_family = ${font}
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -30
    halign = center
    valign = center
    inner_color = rgb(${background})
    outer_color = rgb(${accent})
    font_color = rgb(${foreground})
    check_color = rgb(${accent})
    fail_color = rgb(${error})
    font_family = ${font}
    outline_thickness = 2
    rounding = 12
    placeholder_text = Senha
    fail_text = Tente novamente
}
